"""Automated pose cleaning (Weight Cleanup).

The neutral (closed) pose makes upper/lower lip weights ambiguous, so the
mouth tears when it opens. Closed eyelids have the same problem around thin
eyelid surfaces. The fix is to separate the surfaces on BOTH meshes the same
way, then bind in that pose.

This module makes that fully automatic. The cage carries authored MouthOpen /
CloseEyes guide keys; when the pose is applied the target head
gets a matching pose key generated by a SWITCHED WRAP. The main wrap deforms
the cage onto the head; here the roles are switched and the HEAD is wrapped
onto the cage - once onto the neutral wrapped cage and once onto the cage
wearing its guide pose - both driven by the very same landmark pairs, pinned
exactly. The head's pose key is the DIFFERENCE between those two
registrations, so the head keeps all of its own detail and receives only the
pose change. Both meshes then pose together from one slider - nothing to
sculpt, no masks to paint, no Edit mode.

The sliders are pure intent: nothing is generated and no mesh is touched while
they move, because one solve costs a second or more. The values are turned into
geometry only by the Pose Meshes button (for sculpting in the pose) and by the
bind, which poses behind the scenes, samples it and returns to neutral.

Doing it as a registration is what makes the separation trustworthy at the lip
and eyelid contact lines: each surface is carried by the wrap of its own side,
under the solver's stiffness, instead of asking a nearest-point query which
side a vertex belongs to where the two surfaces touch. Generated keys are
stamped with a fingerprint of the wrap, the guide and the landmarks, so
changing any of them regenerates the key automatically on the next slider
move. Weights are pose-independent, so the final neutral rig is correct.
"""

from contextlib import contextmanager

import numpy as np
import bpy
from mathutils import Vector

from ..core import align, bind as bindmod, tps, wrap as wrapmod
from .op_wrap import (
    WRAPPED_KEY, MOUTH_OPEN_KEY, CLOSE_EYES_KEY,
    MOUTH_CLEAN_GROUP, EYES_CLEAN_GROUP,
)
from .op_weights import _basis_local

# Switched-wrap solver settings. The neutral solve starts from the
# landmark-aligned head and carries it onto the cage surface, so it gets the
# full anneal; the posed solve is warm-started from that result and only has to
# follow the guide pose, so it needs far fewer stages. Neither has to be
# absolutely accurate - only their DIFFERENCE is used.
_NEUTRAL_SOLVE = dict(stages=6, inner=10, stiff_hi=0.92, stiff_lo=0.18,
                      step=0.60, normal_limit=0.10)
_POSED_SOLVE = dict(stages=8, inner=10, stiff_hi=0.45, stiff_lo=0.08,
                    step=0.70, normal_limit=0.10)

# Only the part of the head the guide pose can actually reach takes part in the
# solves; everything else is frozen in BOTH of them, so its pose delta is
# exactly zero. Opening the mouth must not drift the back of the skull, and a
# free vertex would drift, because the second solve re-relaxes the whole mesh.
_REGION_MARGIN_FRAC = 0.12    # halo around the cage verts the guide moves
_REGION_DILATE = 2            # extra edge rings, so the falloff is not abrupt
_DELTA_SMOOTH_ITERS = 12      # de-facet the delta (see _smooth_delta)

_CLEANUP_SPECS = {
    'MOUTH': dict(
        key=MOUTH_OPEN_KEY,
        group=MOUTH_CLEAN_GROUP,
        amount_prop="mouth_open_amount",
        label="mouth",
    ),
    'EYES': dict(
        key=CLOSE_EYES_KEY,
        group=EYES_CLEAN_GROUP,
        amount_prop="eyes_close_amount",
        label="eyes",
    ),
}


def cleanup_spec(feature):
    spec = _CLEANUP_SPECS.get(feature)
    return dict(spec) if spec else None


def _feature_of_key(key_name):
    for feature, spec in _CLEANUP_SPECS.items():
        if key_name == spec["key"]:
            return feature
    return ""


def _has_key(obj, name):
    me = obj.data
    return bool(me.shape_keys and name in me.shape_keys.key_blocks)


def _key_blocks(obj):
    if not obj or obj.type != 'MESH' or obj.data.shape_keys is None:
        return None
    return obj.data.shape_keys.key_blocks


def _set_key_value(obj, key_name, value):
    keys = _key_blocks(obj)
    if keys and key_name in keys:
        key = keys[key_name]
        key.slider_min, key.slider_max = 0.0, 1.0
        key.value = value
        obj.data.update()
        return True
    return False


def _ensure_target_key(target, key_name):
    tme = target.data
    if tme.shape_keys is None:
        target.shape_key_add(name="Basis", from_mix=False)
    if key_name not in tme.shape_keys.key_blocks:
        target.shape_key_add(name=key_name, from_mix=False)
    key = tme.shape_keys.key_blocks[key_name]
    key.slider_min, key.slider_max = 0.0, 1.0
    return key


def _mode_object(context):
    if context.object and context.object.mode != 'OBJECT':
        try:
            bpy.ops.object.mode_set(mode='OBJECT')
        except RuntimeError:
            pass


# ------------------------------------------------- automatic pose transfer ---

def _stamp_prop(key_name):
    return f"mhfrt_cleanup_stamp_{key_name}"


def _landmark_stamp(mh):
    """Fingerprint of the landmark pairs. The switched wrap is driven by them,
    so editing a landmark must regenerate the pose key even when the wrap
    itself was not re-run."""
    if mh is None:
        return "0"
    total = 0.0
    count = 0
    for lm in mh.landmarks:
        if not (lm.has_src and lm.has_tgt):
            continue
        count += 1
        total += sum(float(v) for v in lm.src_co) + sum(float(v) for v in lm.tgt_co)
    return f"{count}:{total:.5f}"


def _pose_stamp(cage, target, key_name, mh=None):
    """Cheap fingerprint of everything the generated pose key depends on:
    the wrapped cage shape, the guide key, the landmark pairs, both meshes'
    sizes and transforms. A mismatch means the key must regenerate."""
    kb = cage.data.shape_keys.key_blocks
    n = len(cage.data.vertices)
    buf = np.empty(n * 3)
    kb[WRAPPED_KEY].data.foreach_get("co", buf)
    wrapped_sum = float(buf.sum())
    kb[key_name].data.foreach_get("co", buf)
    guide_sum = float(buf.sum())
    mats = [_landmark_stamp(mh)]
    for obj in (cage, target):
        mats.extend(f"{float(v):.5f}" for row in obj.matrix_world for v in row)
    # v3: landmark-driven switched wrap (regenerates v1/v2 delta-transfer keys)
    return (f"v3|{cage.name}|{n}|{len(target.data.vertices)}|"
            f"{wrapped_sum:.4f}|{guide_sum:.4f}|" + ",".join(mats))


def _wrap_scale(cage):
    """How much the wrap resized the cage. Guide deltas are authored at the
    ORIGINAL (Ada) scale, but the wrap moves vertices - not the object - so
    on a head bigger or smaller than Ada the raw delta opens the mouth by
    Ada's absolute millimetres: proportionally almost nothing. Every use of
    the guide deltas must be multiplied by this ratio."""
    kb = cage.data.shape_keys.key_blocks
    n = len(cage.data.vertices)
    buf = np.empty(n * 3)
    kb[0].data.foreach_get("co", buf)
    basis = buf.reshape(n, 3)
    size_a = float(np.max(basis.max(0) - basis.min(0)))
    kb[WRAPPED_KEY].data.foreach_get("co", buf)
    wrapped = buf.reshape(n, 3)
    size_b = float(np.max(wrapped.max(0) - wrapped.min(0)))
    if size_a <= 1e-9 or size_b <= 1e-9:
        return 1.0
    return max(size_b / size_a, 1e-3)


def _cage_pose_shapes(cage, key_name):
    """(basis, neutral, posed) cage LOCAL vertex arrays.

    `neutral` is the wrapped shape the artist sees at slider 0; `posed` is that
    same shape carrying the FULL guide pose, scaled to the wrapped head's size
    (the guide is authored at Ada's scale - see _wrap_scale)."""
    me = cage.data
    kb = me.shape_keys.key_blocks
    n = len(me.vertices)
    buf = np.empty(n * 3)
    kb[0].data.foreach_get("co", buf)
    basis = buf.reshape(n, 3).copy()
    kb[WRAPPED_KEY].data.foreach_get("co", buf)
    neutral = buf.reshape(n, 3).copy()
    kb[key_name].data.foreach_get("co", buf)
    guide = buf.reshape(n, 3).copy()
    return basis, neutral, neutral + _wrap_scale(cage) * (guide - basis)


def _to_world(obj, local):
    mw = np.asarray(obj.matrix_world)
    return local @ mw[:3, :3].T + mw[:3, 3]


def _landmark_correspondence(mh, cage, target, basis, cage_shape_local):
    """The EXACT landmark pairs, switched for this wrap.

    The head is the mesh being deformed here, so the head side is the source and
    the cage side is the destination - evaluated on `cage_shape_local`, i.e.
    wherever each landmark sits in the pose being wrapped onto."""
    src, dst = [], []
    for lm in mh.landmarks:
        if not (lm.has_src and lm.has_tgt):
            continue
        vi = int(lm.src_vidx)
        off = (cage_shape_local[vi] - basis[vi]) if 0 <= vi < len(basis) \
            else np.zeros(3)
        src.append(np.asarray(lm.tgt_co, dtype=float))
        dst.append(np.asarray(lm.src_co, dtype=float) + off)
    if not src:
        empty = np.empty((0, 3))
        return empty, empty
    return _to_world(target, np.array(src)), _to_world(cage, np.array(dst))


def _pose_region(tworld, moving_world, margin, ttopo):
    """Head vertices the guide pose can reach: within `margin` of a cage vertex
    the guide actually moves, dilated a couple of edge rings so the frozen
    boundary sits well away from the lips."""
    n = len(tworld)
    active = np.zeros(n, dtype=bool)
    if not len(moving_world):
        return active
    m2 = margin * margin
    mv2 = (moving_world ** 2).sum(axis=1)
    step = 1024
    for s in range(0, n, step):
        chunk = tworld[s:s + step]
        # |a-b|^2 without materialising the (chunk x moving x 3) intermediate
        d2 = ((chunk ** 2).sum(axis=1)[:, None] + mv2[None, :]
              - 2.0 * (chunk @ moving_world.T))
        active[s:s + step] = d2.min(axis=1) <= m2
    e = ttopo["edges"]
    for _ in range(_REGION_DILATE):
        grow = active.copy()
        grow[e[active[e[:, 1]], 0]] = True
        grow[e[active[e[:, 0]], 1]] = True
        active = grow
    return active


def _carry_guide_delta(P_neutral, active, bvh_neutral, ctris,
                       cage_neutral_w, cage_posed_w):
    """The cage's pose motion, carried to each registered head vertex.

    This is only the STARTING position for the posed solve, but it is what
    makes that solve possible at all: a closest-point pull cannot open a SEALED
    mouth, because the two lips start in the same place and neither can tell
    which side of the open cage it belongs to. After the neutral solve every
    active head vertex sits ON the neutral cage surface, so a plain lookup
    gives the triangle it belongs to with the ambiguity already resolved - the
    registration, under the landmark pins, has decided each vertex's side. The
    posed solve then polishes this opened shape onto the real posed surface."""
    out = np.zeros_like(P_neutral)
    guide = cage_posed_w - cage_neutral_w
    # Gather hits in the loop (BVH queries only), then do the barycentric maths
    # for all of them at once - per-vertex numpy calls here cost seconds.
    idx_list, loc_list, vert_list = [], [], []
    for i in np.nonzero(active)[0]:
        loc, _nor, tri_index, _d = bvh_neutral.find_nearest(Vector(P_neutral[i]))
        if loc is None or tri_index is None:
            continue
        vert_list.append(i)
        idx_list.append(tri_index)
        loc_list.append((loc.x, loc.y, loc.z))
    if not vert_list:
        return out

    verts = np.array(vert_list, dtype=np.int64)
    tri = ctris[np.array(idx_list, dtype=np.int64)]
    p = np.array(loc_list, dtype=float)
    a, b, c = (cage_neutral_w[tri[:, 0]], cage_neutral_w[tri[:, 1]],
               cage_neutral_w[tri[:, 2]])
    v0, v1, v2 = b - a, c - a, p - a
    d00 = (v0 * v0).sum(axis=1)
    d01 = (v0 * v1).sum(axis=1)
    d11 = (v1 * v1).sum(axis=1)
    d20 = (v2 * v0).sum(axis=1)
    d21 = (v2 * v1).sum(axis=1)
    den = d00 * d11 - d01 * d01
    den = np.where(np.abs(den) < 1e-12, 1.0, den)
    vv = (d11 * d20 - d01 * d21) / den
    ww = (d00 * d21 - d01 * d20) / den
    bary = np.clip(np.stack([1.0 - vv - ww, vv, ww], axis=1), 0.0, None)
    bary /= np.maximum(bary.sum(axis=1, keepdims=True), 1e-12)
    out[verts] = (bary[:, 0:1] * guide[tri[:, 0]]
                  + bary[:, 1:2] * guide[tri[:, 1]]
                  + bary[:, 2:3] * guide[tri[:, 2]])
    return out


def _smooth_delta(delta, ttopo, active, iterations=_DELTA_SMOOTH_ITERS, lam=0.5):
    """Light Laplacian smoothing of the POSE DELTA (never of the head itself).

    Snapping onto a low-poly cage quantises positions to cage facets, and
    neighbouring head vertices can land on different facets in the two solves,
    which surfaces as facet-scale jitter in their difference. A pose is a
    low-frequency quantity, so smoothing the delta removes that jitter without
    touching the head's own detail - that detail lives in the basis this delta
    is added to. Frozen vertices stay exactly zero."""
    n = ttopo["n"]
    e = ttopo["edges"]
    deg = ttopo["degree"]
    out = delta.copy()
    out[~active] = 0.0
    for _ in range(max(0, int(iterations))):
        acc = np.empty_like(out)
        for ax in range(3):
            acc[:, ax] = (np.bincount(e[:, 0], weights=out[e[:, 1], ax],
                                      minlength=n)
                          + np.bincount(e[:, 1], weights=out[e[:, 0], ax],
                                        minlength=n))
        nb = acc / deg
        out[active] += lam * (nb[active] - out[active])
        out[~active] = 0.0
    return out


def _pin_vertices(tlocal, mh):
    """The target vertex nearest each landmark's head-side point. Pinning these
    is what makes the switched wrap land on the EXACT landmarks."""
    out = []
    for lm in mh.landmarks:
        if not (lm.has_src and lm.has_tgt):
            continue
        p = np.asarray(lm.tgt_co, dtype=float)
        out.append(int(((tlocal - p) ** 2).sum(axis=1).argmin()))
    return out


def _generate_target_key(context, cage, target, key_name):
    """Give the head its open-mouth / closed-eyes shape by a SWITCHED WRAP.

    The main wrap deforms the cage onto the head. Here the roles are switched:
    the HEAD is wrapped onto the cage - once onto the neutral wrapped cage, and
    once onto the cage wearing its authored guide pose - both driven by the very
    same landmark pairs, pinned exactly. The pose key is the DIFFERENCE between
    those two registrations.

    Using the difference is what preserves the head's own detail: wrapping a
    dense head onto a low-poly cage would resample it down to cage resolution,
    but that error is present in both solves and cancels, leaving only the pose
    change. The posed solve is warm-started from the neutral one, so the two are
    strongly correlated and their difference is smooth. Nothing anywhere samples
    a nearest point, which is why the lip and eyelid contact lines - the exact
    place the old delta transfer misfired and needed a repair pass - come out
    right: each surface is carried by the registration of its own side.

    Returns how many vertices moved."""
    mh = getattr(context.scene, "mhfrt", None) if context and context.scene \
        else None
    if mh is None:
        return 0
    me = cage.data
    ctris = bindmod.triangles_of(me)
    if not len(ctris):
        return 0

    basis, neutral_local, posed_local = _cage_pose_shapes(cage, key_name)
    neutral_world = _to_world(cage, neutral_local)
    posed_world = _to_world(cage, posed_local)

    tlocal = _basis_local(target)
    if not len(tlocal):
        return 0
    tworld = _to_world(target, tlocal)
    ttopo = wrapmod.topology(target.data)

    src_pts, dst_neutral = _landmark_correspondence(
        mh, cage, target, basis, neutral_local)
    _src_posed, dst_posed = _landmark_correspondence(
        mh, cage, target, basis, posed_local)
    if len(src_pts) < 3:
        return 0

    # A) bring the head into the cage's frame from the landmarks alone, exactly
    #    the way the main wrap does it, so the surface solve only has to polish
    s, R, t = align.similarity_transform(src_pts, dst_neutral)
    P = align.apply_similarity(tworld, s, R, t)
    if len(src_pts) >= 4:
        src_a = align.apply_similarity(src_pts, s, R, t)
        try:
            P = tps.tps_apply(tps.tps_fit(src_a, dst_neutral, reg=1e-6), P)
        except np.linalg.LinAlgError:
            pass

    size = max(float(max(cage.dimensions)), 1e-6)
    max_dist = float(getattr(mh, "wrap_maxdist_frac", 0.1)) * size

    # B) restrict both solves to the region the guide can reach. Frozen
    #    vertices are pinned identically in both, so their delta is exactly 0.
    guide_move = np.linalg.norm(posed_local - neutral_local, axis=1)
    gmax = float(guide_move.max()) if len(guide_move) else 0.0
    if gmax <= 0.0:
        return 0
    # Ignore the guide's long numerical tail: a cage vertex moving a fraction
    # of a millimetre contributes nothing to the pose but would drag the whole
    # face into the active region (and with it, the solve cost).
    moving = guide_move > max(0.10 * gmax, 0.002 * size)
    if not moving.any():
        moving = guide_move > 0.10 * gmax
    if not moving.any():
        return 0
    active = _pose_region(P, _to_world(cage, posed_local)[moving],
                          _REGION_MARGIN_FRAC * size, ttopo)
    if not active.any():
        return 0
    frozen = {int(i): P[i] for i in np.nonzero(~active)[0]}

    pin_idx = _pin_vertices(tlocal, mh)
    pins_neutral = dict(frozen)
    pins_posed = dict(frozen)
    for k, v in enumerate(pin_idx):
        pins_neutral[int(v)] = dst_neutral[k]
        pins_posed[int(v)] = dst_posed[k]

    # C) head -> neutral wrapped cage
    bvh_neutral = bindmod.build_bvh(neutral_world, ctris)
    P_neutral = wrapmod.register_surface(
        P, ttopo, bvh_neutral, pins_neutral, max_dist=max_dist,
        **_NEUTRAL_SOLVE)

    # D) open the registered head by the cage's own pose motion, so the posed
    #    solve starts from an already-separated mouth instead of a sealed one
    P_init = P_neutral + _carry_guide_delta(
        P_neutral, active, bvh_neutral, ctris, neutral_world, posed_world)
    P_init[~active] = P_neutral[~active]

    # E) the same head -> the cage wearing the guide pose: now only a polish
    P_posed = wrapmod.register_surface(
        P_init, ttopo, bindmod.build_bvh(posed_world, ctris), pins_posed,
        max_dist=max_dist, **_POSED_SOLVE)

    # F) only the pose difference ever reaches the head's own vertices
    tmwi3 = np.asarray(target.matrix_world.inverted())[:3, :3]
    delta = _smooth_delta(P_posed - P_neutral, ttopo, active)
    delta_local = delta @ tmwi3.T
    out = tlocal + delta_local

    key = _ensure_target_key(target, key_name)
    key.data.foreach_set("co", np.ascontiguousarray(out.reshape(-1)))
    target.data.update()
    target.data[_stamp_prop(key_name)] = _pose_stamp(cage, target, key_name, mh)
    tsize = max(float(max(target.dimensions)), 1e-6)
    return int((np.linalg.norm(delta_local, axis=1) > 1e-4 * tsize).sum())


def ensure_cleanup_ready(context, feature, operator=None):
    """Validate the pair and auto-(re)generate the target's pose key when it
    is missing or stale. Returns the spec dict, or None (reporting through
    `operator` when one is given)."""
    def _err(msg):
        if operator is not None:
            operator.report({'ERROR'}, msg)
        return None

    spec = cleanup_spec(feature)
    if spec is None:
        return _err("Unknown cleanup feature")
    mh = getattr(context.scene, "mhfrt", None) if context and context.scene \
        else None
    if mh is None:
        return None
    cage, target = mh.cage, mh.target
    if not cage or not target or cage == target:
        return _err("Set Head Cage and Head Target first")
    key_name = spec["key"]
    if not _has_key(cage, key_name):
        return _err(f"Cage has no '{key_name}' shape key")
    if not _has_key(cage, WRAPPED_KEY):
        return _err("Do the neutral Wrap first")

    ckb = cage.data.shape_keys.key_blocks
    ckb[WRAPPED_KEY].value = 1.0
    # slider_max is managed by apply_cleaning_amount (it can exceed 1.0 on a
    # head larger than Ada, where the guide delta must be over-driven)
    ckb[key_name].slider_min = 0.0

    # the switched wrap needs the landmarks the neutral wrap was built from
    if len([lm for lm in mh.landmarks if lm.has_src and lm.has_tgt]) < 3:
        return _err("Weight Cleanup needs the landmark pairs used for the wrap")

    stamp = _pose_stamp(cage, target, key_name, mh)
    if (not _has_key(target, key_name)
            or str(target.data.get(_stamp_prop(key_name), "")) != stamp):
        _generate_target_key(context, cage, target, key_name)
    return spec


def apply_cleaning_amount(context, key_name, amount, operator=None):
    """Pose the cage AND the head together at `amount`. The head's pose key is
    generated automatically (and regenerated whenever the wrap changed), so
    there is nothing to sculpt.

    This is deliberately NOT a slider hook: generating the switched-wrap pose
    key and re-evaluating both meshes takes a second or more, which is
    unusable on every mouse move. The sliders only store a value; this runs
    from the Pose Meshes button and from the bind (see sync_cleanup_pose)."""
    mh = getattr(context.scene, "mhfrt", None) if context and context.scene \
        else None
    if mh is None:
        return False
    # a live session sims the posed surface against a snapshot of the head -
    # changing the pose under it would corrupt the write-back, so end it
    from .op_live import stop_running
    stop_running()
    value = max(0.0, min(1.0, float(amount)))
    if value > 0.0:
        feature = _feature_of_key(key_name)
        if feature and ensure_cleanup_ready(context, feature, operator) is None:
            return False                # not ready (no wrap yet): stay neutral
    # the head's generated key already carries wrap-scaled deltas
    _set_key_value(mh.target, key_name, value)
    # the cage's authored guide is at the ORIGINAL Ada scale: drive its value
    # by slider x wrap-scale so both meshes open by the same, head-sized
    # amount (the value is the delta multiplier)
    keys = _key_blocks(mh.cage)
    if keys and key_name in keys:
        key = keys[key_name]
        if value <= 0.0:
            key.value = 0.0
        else:
            scale = _wrap_scale(mh.cage)
            key.slider_min = 0.0
            key.slider_max = max(1.0, scale)
            key.value = value * scale
        mh.cage.data.update()
    return True


def sync_cleanup_pose(context, operator=None):
    """Put both meshes into the pose the cleanup sliders currently ask for.

    The one place slider values become real geometry. Two callers, and they
    must agree: the Pose Meshes button (the artist wants to see the pose so
    they can sculpt or brush in it) and the bind, which poses behind the
    scenes, samples that pose and returns to neutral - so binding gives the
    same result whether or not the button was ever pressed.

    Returns the labels of the features actually posed."""
    mh = getattr(context.scene, "mhfrt", None) if context and context.scene \
        else None
    if mh is None:
        return []
    posed = []
    for spec in _CLEANUP_SPECS.values():
        amount = float(getattr(mh, spec["amount_prop"], 0.0))
        # a zero slider still runs: that is how the pose is taken back off
        if apply_cleaning_amount(context, spec["key"], amount,
                                 operator if amount > 1e-6 else None) \
                and amount > 1e-6:
            posed.append(spec["label"])
    return posed


def _visible_pose_state(*objects):
    """Every shape-key value and active-key index on these meshes."""
    state = []
    for obj in objects:
        if obj is None:
            continue
        try:
            keys = obj.data.shape_keys
            state.append((obj, obj.active_shape_key_index,
                          [(k, float(k.value)) for k in keys.key_blocks]
                          if keys else []))
        except (AttributeError, ReferenceError):
            continue
    return state


def _restore_pose_state(state):
    for obj, active_index, values in state:
        try:
            changed = False
            for key, value in values:
                if abs(key.value - value) > 1e-9:
                    key.value = value
                    changed = True
            if obj.active_shape_key_index != active_index:
                obj.active_shape_key_index = active_index
            if changed:
                obj.data.update()
        except (AttributeError, ReferenceError, RuntimeError):
            continue


@contextmanager
def cleanup_pose_for_sampling(context, operator=None):
    """Pose both meshes to the cleanup sliders, then put the view back.

    The bind has to SAMPLE the cleanup pose - lips apart, lids apart - or the
    correspondence it builds welds them shut.  What it must not do is show it.
    Posing writes real shape-key values, and an artist who left the sliders at
    0.6 does not expect Re-Bind to leave their head sitting there with its mouth
    open, or to flash it on the way past; the pose is a step in the bind, not a
    change to their scene.  Only Pose Meshes is allowed to change what is on
    screen.

    So the exact visible state - every key value AND the active key index,
    which ``ensure_cleanup_ready`` moves when it regenerates the head's pose key
    - is snapshotted here and put back in a ``finally``.  That last part is the
    point: before this, a bind that raised halfway left the meshes posed with no
    way back but re-dialling the sliders.

    Yields the labels of the features actually posed (empty when the sliders are
    at zero, or when the pose could not be generated - the caller reports that
    rather than binding a pose it did not get).
    """
    state = _visible_pose_state(
        *(o for o in (getattr(context.scene.mhfrt, "cage", None),
                      getattr(context.scene.mhfrt, "target", None))))
    try:
        yield sync_cleanup_pose(context, operator)
    finally:
        _restore_pose_state(state)


class MHFRT_OT_apply_cleanup_pose(bpy.types.Operator):
    bl_idname = "mhfrt.apply_cleanup_pose"
    bl_label = "Pose Meshes"
    bl_description = (
        "Show the pose the sliders above ask for on the cage AND your head, so "
        "you can sculpt or smooth-brush it before binding. Optional: Re-Bind "
        "always uses the slider values whether or not you press this")
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        mh = getattr(context.scene, "mhfrt", None)
        return bool(mh and mh.cage and mh.target and mh.cage != mh.target)

    def execute(self, context):
        _mode_object(context)
        posed = sync_cleanup_pose(context, self)
        self.report({'INFO'},
                    ("Posed: " + " + ".join(posed)) if posed
                    else "Both meshes back to neutral")
        return {'FINISHED'}


def ensure_cleanup_pose(context, operator, feature, reset_amount=False):
    """Compatibility entry for the live/brush cleanup paths: validate the
    pair, make sure the target pose key exists, and sync both meshes to the
    cleanup slider."""
    from .op_live import stop_running
    stop_running()          # poses the cage's shape keys
    _mode_object(context)
    spec = ensure_cleanup_ready(context, feature, operator)
    if spec is None:
        return None
    mh = context.scene.mhfrt
    prop_name = spec["amount_prop"]
    if reset_amount and prop_name:
        setattr(mh, prop_name, 0.5)
    amount = getattr(mh, prop_name, 0.5)
    apply_cleaning_amount(context, spec["key"], amount)
    target = mh.target
    target.active_shape_key_index = \
        target.data.shape_keys.key_blocks.find(spec["key"])
    target.data.update()
    return spec


_classes = (MHFRT_OT_apply_cleanup_pose,)


def register():
    for c in _classes:
        bpy.utils.register_class(c)


def unregister():
    for c in reversed(_classes):
        bpy.utils.unregister_class(c)
